pipeline:
  name: Build maven-azure-integration
  identifier: Build_maven_azure_integration_1769592288506
  projectIdentifier: appdemo
  orgIdentifier: default
  stages:
    - stage:
        name: Build
        identifier: Build
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: Echo Welcome Message
                  identifier: Echo_Welcome_Message
                  spec:
                    shell: Sh
                    command: echo "Welcome to Harness CI"
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Docker
            spec:
              harnessImageConnectorRef: account.harnessImage
  properties:
    ci:
      codebase:
        connectorRef: account.github
        repoName: maven-azure-integration
        build: <+input>
